# Jekyll Configuration for GitHub Pages

title: Hosted Documents
description: A Github workflow that automatically publishes markdown files as a webpage.
baseurl: "/Obsidian_to_GitPage_Workflow"
url: "https://PatrickEasy.github.io"
date: 2025-12-11
author: PatrickEasy

# Theme
theme: minima

# Build settings
markdown: kramdown

# Include files with spaces in names
include:
  - "Christmas Presents.md"

# Exclude files from processing
exclude:
  - .git
  - .github
  - README.md
  - LICENSE
